services:
  - type: web
    name: monitor747
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_KEY
        sync: false